#:schema node_modules/wrangler/config-schema.json
name = "pinger"
main = "src/index.ts"
compatibility_date = "2024-10-11"
compatibility_flags = ["nodejs_compat_v2"]

[observability]
enabled = true

[triggers]
crons = ["0 0 */3 * *"]
